language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install lpeg 0.10.2
  - luarocks install moonscript
  - luarocks make

before_script:
  - createdb -U postgres lapis_test
  - mysql -e 'create database lapis_test;'

script: 
  - busted


